export const products = [
  {
    id: 1,
    image: "",
    title: "HAVIT HV-G92 Gamepad",
    description: "",
    offerprice: 280,
    mainprice: 400,
    category: "electronics",
    status: "flashSale",
    rating: 120,     
    stars: 2        
  },
  {
    id: 2,
    image: "",
    title: "AK-900 Wired Keyboard",
    description: "",
    offerprice: 0,
    mainprice: 1160,
    category: "electronics",
    status: "flashSale",
    rating: 80,
    stars: 4.2
  },
  {
    id: 3,
    image: "",
    title: "IPS LCD Gaming Monitor",
    description: "",
    offerprice: 370,
    mainprice: 400,
    category: "electronics",
    status: "flashSale",
    rating: 150,
    stars: 4.7
  },
  {
    id: 4,
    image: "",
    title: "S-Series Comfort Chair",
    description: "",
    offerprice: 375,
    mainprice: 400,
    category: "furniture",
    status: "flashSale",
    rating: 60,
    stars: 4.0
  },
  {
    id: 5,
    image: "",
    title: "S-Series Comfort Chair",
    description: "",
    offerprice: 375,
    mainprice: 400,
    category: "furniture",
    status: "flashSale",
    rating: 95,
    stars: 4.3
  },
  {
    id: 6,
    image: "",
    title: "The north coat",
    description: "",
    offerprice: 260,
    mainprice: 360,
    category: "fashion",
    status: "bestSelling",
    rating: 200,
    stars: 4.6
  },
  {
    id: 7,
    image: "",
    title: "Gucci duffle bag",
    description: "",
    offerprice: 960,
    mainprice: 1160,
    category: "fashion",
    status: "bestSelling",
    rating: 50,
    stars: 4.1
  },
  {
    id: 8,
    image: "",
    title: "RGB liquid CPU Cooler",
    description: "",
    offerprice: 160,
    mainprice: 170,
    category: "electronics",
    status: "bestSelling",
    rating: 140,
    stars: 4.4
  },
  {
    id: 9,
    image: "",
    title: "Small Bookshelf",
    description: "",
    offerprice: 360,
    mainprice: 400,
    category: "furniture",
    status: "bestSelling",
    rating: 70,
    stars: 3.9
  },
  {
    id: 10,
    image: "",
    title: "Breed Dry Dog Food",
    description: "",
    offerprice: 100,
    mainprice: 120,
    category: "pets",
    status: "normal",
    rating: 30,
    stars: 4.0
  },
  {
    id: 11,
    image: "",
    title: "CANON EOS DSLR Camera",
    description: "",
    offerprice: 360,
    mainprice: 500,
    category: "electronics",
    status: "normal",
    rating: 250,
    stars: 4.8
  },
  {
    id: 12,
    image: "",
    title: "Asus FHD Gaming Laptop",
    description: "",
    offerprice: 700,
    mainprice: 1000,
    category: "electronics",
    status: "normal",
    rating: 180,
    stars: 4.5
  },
  {
    id: 13,
    image: "",
    title: "Curology Product Set",
    description: "",
    offerprice: 500,
    mainprice: 600,
    category: "cosmetics",
    status: "normal",
    rating: 40,
    stars: 4.1
  },
  {
    id: 14,
    image: "",
    title: "Kids Electric Car",
    description: "",
    offerprice: 960,
    mainprice: 1200,
    category: "toys",
    status: "normal",
    rating: 65,
    stars: 4.2
  },
  {
    id: 15,
    image: "",
    title: "Jr. Zoom Soccer Cleats",
    description: "",
    offerprice: 1160,
    mainprice: 1300,
    category: "sports",
    status: "normal",
    rating: 75,
    stars: 4.4
  },
  {
    id: 16,
    image: "",
    title: "GP11 Shooter USB Gamepad",
    description: "",
    offerprice: 550,
    mainprice: 600,
    category: "electronics",
    status: "normal",
    rating: 90,
    stars: 4.3
  },
  {
    id: 17,
    image: "",
    title: "Quilted Satin Jacket",
    description: "",
    offerprice: 660,
    mainprice: 750,
    category: "fashion",
    status: "normal",
    rating: 110,
    stars: 4.5
  }
];
